### ISSUE TITLE
Problem statement review - PID Controller

### ISSUE THREAD

**Issue by muralidn** [muralidn/CAS741-Fall20#1]
@smiths 

Please review the following problem statement and share your feedback,

https://github.com/muralidn/CAS741-Fall20/blob/master/docs/ProblemStatement/PID_Controller.pdf

**Comment by muralidn** [comment]
@smiths 
The following artifacts were updated according to the latest Problem Statement Checklist (23-Sep-2020),

Commit 1: 123d2ae6226cef73d86f9841b2d55eef50d5ea9f
Commit 2:  ed89f11eb9e7f82ddce4f134634f038d806d8fc9

- https://github.com/muralidn/CAS741-Fall20/blob/master/docs/ProblemStatement/PID_Controller.pdf
- https://github.com/muralidn/CAS741-Fall20/blob/master/docs/ProblemStatement/PID_Controller.tex

The specific updates that were made are,

- Included the Comments.tex file. 
- Wrapped text in the .tex file to 80 chars. 
- Corrected grammatical mistakes.
- Added reference to Drasil.

Please review and revert if you find any issues.

**Comment by smiths** [comment]
@muralidn, great to see you preemptively address the problem statement comments!  Thank you.

I have the following comments on the current version:

- The revision history would fit better on the page if you reduced the width of the middle column (using `p` with a width)
- The filename should match the blank project template (for standardization purposes)

I don't see any other issues.  Looks good.

Your problem statement is approved.  :smile:
