### ISSUE TITLE
Elaborate user characteristics

### ISSUE THREAD

**Issue by muralidn** [muralidn/CAS741-Fall20#10]
The intended reader and user characteristics sound similar. The intended reader characteristics actually requires complete knowledge of control systems. Requires rewording.

**Comment by muralidn** [comment]
The issue has been addressed with commit id 41ad20c. Closing the issue.

**Comment by smiths** [comment]
@muralidn, good use of the issue tracker!  However, it is better if you have more frequent and smaller commits.  If you have one commit to close one issue, then it is easier for future traceability.

**Comment by muralidn** [comment]
Thanks for the review Dr. @smiths!.

I realized the mistake after the fact when I was peer-reviewing other SRS. 

In the future, I will ensure I have one commit per issue.

**Comment by smiths** [comment]
Sounds good!  The best practices for using version control are something that we learn over time with experience.  I'm still learning too!
