### ISSUE TITLE
Adapt statement in section 1.2 Table of Symbols

### ISSUE THREAD

**Issue by shinsid** [muralidn/CAS741-Fall20#18]
Hi Naveen,

According to my understanding, the below-highlighted line should be adapted to your project. As the reader might not know anything about SWHS project or documentation.

![Screenshot from 2020-10-13 22-14-49](https://user-images.githubusercontent.com/12082585/95935732-f4081c00-0da1-11eb-8de9-97e96ede306f.png)

**Comment by muralidn** [comment]
Thanks! Issue addressed with commit b12e5f584f491edd5b2d083e8955277c46773a02.
