### ISSUE TITLE
Writing '-' for the unit should be enough

### ISSUE THREAD

**Issue by shinsid** [muralidn/CAS741-Fall20#19]
Hi Naveen,

Just a suggestion - I was thinking, maybe writing '-' in unit column should be enough for following symbols and you could mention in the description column that these are constants. **(I can be wrong in this :-) )**

![Screenshot from 2020-10-13 22-19-22](https://user-images.githubusercontent.com/12082585/95935842-329dd680-0da2-11eb-881a-fc1c246cf0cc.png)

**Comment by muralidn** [comment]
@shinsid, thanks for the comment, but I am going to leave this as-is for readability. As such I think this is ok.
