### ISSUE TITLE
Table of Symbols going off limits on page

### ISSUE THREAD

**Issue by shinsid** [muralidn/CAS741-Fall20#20]
The table of symbols is going off-limits on the page.

![Screenshot from 2020-10-13 22-23-11](https://user-images.githubusercontent.com/12082585/95936071-b952b380-0da2-11eb-9d11-37a60e58a642.png)

**Comment by muralidn** [comment]
Thanks! Issue addressed with commit b12e5f584f491edd5b2d083e8955277c46773a02.
