### ISSUE TITLE
Typo in Abbreviations and Acronyms table

### ISSUE THREAD

**Issue by shinsid** [muralidn/CAS741-Fall20#21]
A small typo in - this should be 'Et cetera'. Also, maybe this is not needed as it is a very universal thing.

![Screenshot from 2020-10-13 22-33-23](https://user-images.githubusercontent.com/12082585/95936674-23b82380-0da4-11eb-8668-6f00ba95917d.png)

**Comment by muralidn** [comment]
Thanks! Issue addressed with commit b12e5f584f491edd5b2d083e8955277c46773a02. 

I have corrected the typo but leaving the definition as is just in case.
