### ISSUE TITLE
PID controller abbreviation is not needed

### ISSUE THREAD

**Issue by shinsid** [muralidn/CAS741-Fall20#22]
'PID controller' abbreviation is not needed as you have one for 'PID' - it is not adding any new information.

![Screenshot from 2020-10-13 22-35-31](https://user-images.githubusercontent.com/12082585/95936814-70036380-0da4-11eb-8158-265a9e4bf53e.png)

**Comment by muralidn** [comment]
Thanks! Issue addressed with commit b12e5f584f491edd5b2d083e8955277c46773a02.

Removed the abbreviation.
