### ISSUE TITLE
Scope of requirements - A small question and a likely typo 

### ISSUE THREAD

**Issue by shinsid** [muralidn/CAS741-Fall20#23]
1. The use of word control twice looks like a typo

2. I was not sure what do you mean by 'Summer' - does it mean 'Summing Point' or something like this?

![Screenshot from 2020-10-13 22-38-08](https://user-images.githubusercontent.com/12082585/95936994-ca042900-0da4-11eb-8a3c-e8caa547b992.png)

**Comment by muralidn** [comment]
Thanks! Issue addressed with commit b12e5f584f491edd5b2d083e8955277c46773a02.

Fixed the control typo, and changed Summer to Summing Point.
