### ISSUE TITLE
Rephrasing might help here

### ISSUE THREAD

**Issue by shinsid** [muralidn/CAS741-Fall20#24]
The highlighted part can be rephrased to make it more clear.

![Screenshot from 2020-10-13 22-40-35](https://user-images.githubusercontent.com/12082585/95937153-223b2b00-0da5-11eb-9733-9456fcd8a0f4.png)

**Comment by muralidn** [comment]
Updated the wording to change to a 4th-year undergraduate. 

Issue addressed with commit b12e5f584f491edd5b2d083e8955277c46773a02.
