### ISSUE TITLE
System Context diagram can be improvised

### ISSUE THREAD

**Issue by shinsid** [muralidn/CAS741-Fall20#26]
In your project, you have two things as I understood - 

1. A control variable - output of PID controller
2. A process variable - output of PID control loop

Just a suggestion(could be wrong here) - I think it would help if you could capture both information in the System Context diagram in some way. 

![Screenshot from 2020-10-13 22-43-46](https://user-images.githubusercontent.com/12082585/95937350-97a6fb80-0da5-11eb-9f00-f72f8d8a83fc.png)

**Comment by muralidn** [comment]
Did not change the figure, but added a definition for PID control loop in the definition section.

Issue addressed with commit b12e5f5.
