### ISSUE TITLE
A small question

### ISSUE THREAD

**Issue by shinsid** [muralidn/CAS741-Fall20#27]
Does 'PowerPlant' and 'PID control loop' point to the same thing as they both output Process Variable? Would it be worth to clarify it somewhere?

![Screenshot from 2020-10-13 22-49-07](https://user-images.githubusercontent.com/12082585/95937695-582cdf00-0da6-11eb-90fd-d5c9bf4f39fd.png)

**Comment by muralidn** [comment]
Same fix as in #26 - Added definition for PID control loop. 

Issue addressed with commit b12e5f584f491edd5b2d083e8955277c46773a02.
