### ISSUE TITLE
More clear GS1

### ISSUE THREAD

**Issue by shinsid** [muralidn/CAS741-Fall20#29]
I think writing what's the output would make the goal statement **1** more clear if someone is directly reading Goal statements.

![Screenshot from 2020-10-13 22-53-26](https://user-images.githubusercontent.com/12082585/95938007-f6b94000-0da6-11eb-85a2-817e6d796ec7.png)

**Comment by muralidn** [comment]
Added more context to the goal statements for better understanding.

Thanks! Issue addressed with commit b12e5f584f491edd5b2d083e8955277c46773a02.
