### ISSUE TITLE
Use of 'T' in DD3

### ISSUE THREAD

**Issue by shinsid** [muralidn/CAS741-Fall20#30]
Would a small 't' instead of 'T' make more sense to be consistent throughout the document? 

Also, 'T' will clash with the abbreviation for 'Theoretical model'

This also follows in IM2.

![Screenshot from 2020-10-13 22-55-27](https://user-images.githubusercontent.com/12082585/95938118-36802780-0da7-11eb-90ce-5180ffd4e289.png)

**Comment by muralidn** [comment]
't' cannot be used here since that is the integral limit. Changed T to "Tau" to avoid conflicts with Theoretical mode. 

Issue addressed with commit b12e5f584f491edd5b2d083e8955277c46773a02.
