### ISSUE TITLE
A small typo in equation

### ISSUE THREAD

**Issue by shinsid** [muralidn/CAS741-Fall20#32]
I think whole term 'u(t)' should be under the squareroot.

![Screenshot from 2020-10-13 22-59-48](https://user-images.githubusercontent.com/12082585/95938414-d63db580-0da7-11eb-9998-9e108fbc3349.png)

**Comment by muralidn** [comment]
Thanks! Issue addressed with commit b12e5f584f491edd5b2d083e8955277c46773a02.
