### ISSUE TITLE
What is x(t)?

### ISSUE THREAD

**Issue by tingyuw** [muralidn/CAS741-Fall20#33]
You mentioned that x(t) is your input in DD2, and you use this value to calculate PID term. But I was wondering how do you get the value and which input it refer to? If you use this mathematical value in your equation, I think you need to put it in the table of symbols, so that the readers could understand what it is and where it comes from.

**Comment by muralidn** [comment]
x(t) is just a generic input signal to demonstrate the formulae. I have added this to the signal definition table.

Issue addressed with commit b12e5f584f491edd5b2d083e8955277c46773a02.
