### ISSUE TITLE
section 4.2.7

### ISSUE THREAD

**Issue by tingyuw** [muralidn/CAS741-Fall20#34]
You mentioned in the section 4.2.7 that your output response of the power plant must reach the set point. Does it mean that the final y(t) will equal to SP? I think this section is a little ambiguous. It isn't clear enough for the readers to know directly what is the correct solution and what isn't.

**Comment by muralidn** [comment]
Thanks for pointing this out.  After a lot of thought, I have concluded that determining the correct solution is the user's responsibility, not the software's responsibility. Therefore I have modified the goal statement and removed the corresponding NFR.
