### ISSUE TITLE
DD6 step time

### ISSUE THREAD

**Issue by tingyuw** [muralidn/CAS741-Fall20#35]
You mentioned that the tstep is equivalent to the total time of the system response. Do you mean the total time of each iteration or the total time of all iterations(Tsim?). From my understanding, tstep will still reach Tsim in the end, but I'm just a little confused about which one do you mean in this text.

**Comment by muralidn** [comment]
tstep is the time around one iteration. In a real-world analogy, tstep is equivalent to the sum of all the delays in the system. I have modified the description to make this more clear. 

Thanks! Issue addressed with commit b12e5f584f491edd5b2d083e8955277c46773a02.
