### ISSUE TITLE
physical system description

### ISSUE THREAD

**Issue by tingyuw** [muralidn/CAS741-Fall20#36]
A small question about figure 2. What are the meaning of the '+' and '-' symbol in the circle? Positive and negative values? But y(t) can't be negative does it? Just out of curiosity because I can't figure out what they supposed to mean.

![image](https://user-images.githubusercontent.com/47548045/96015697-dbd1e480-0e15-11eb-9e07-9c2402a6860f.png)

**Comment by muralidn** [comment]
The + and - in the Summing point are not positive or negative signals, they denote whether to consider the signal as positive or negative feedback. In this case, it means e(t) = SP - y(t). 

Here is a good read if you are interested, https://www.tutorialspoint.com/control_systems/control_systems_block_diagrams.htm.

No changes were made for this issue.
