### ISSUE TITLE
Some typos

### ISSUE THREAD

**Issue by tingyuw** [muralidn/CAS741-Fall20#37]
1. You mentioned 'is' twice in DD5 description.
![image](https://user-images.githubusercontent.com/47548045/96016251-864a0780-0e16-11eb-8584-b9dd461ec3ba.png)

2. You should modify the description of the section table of symbols to your system.
![image](https://user-images.githubusercontent.com/47548045/96016586-e9d43500-0e16-11eb-9ac3-ab2c7262326d.png)

**Comment by muralidn** [comment]
Thanks! Issue addressed with commit b12e5f5.
