### ISSUE TITLE
Vnv plan review - Dr. Smith

### ISSUE THREAD

**Issue by muralidn** [muralidn/CAS741-Fall20#43]
Hello Dr. @smiths, please review the Verification and Validation plan for my project.

Artifacts:

https://github.com/muralidn/CAS741-Fall20/blob/master/docs/VnVPlan/VnVPlan.pdf
https://github.com/muralidn/CAS741-Fall20/blob/master/docs/VnVPlan/VnVPlan.tex

**Comment by smiths** [comment]
Minor typos are corrected in bc06c86.

**Comment by smiths** [comment]
Comments on the VnV plan are available in fd6087d.
