### ISSUE TITLE
Vnv review - Ting Yu

### ISSUE THREAD

**Issue by muralidn** [muralidn/CAS741-Fall20#44]
Hello @tingyuw, please review the Verification and Validation plan for my project.

Artifacts:

https://github.com/muralidn/CAS741-Fall20/blob/master/docs/VnVPlan/VnVPlan.pdf
https://github.com/muralidn/CAS741-Fall20/blob/master/docs/VnVPlan/VnVPlan.tex

**Comment by tingyuw** [comment]
Hello @muralidn,
I have reviewed your VnV plan. Hope those comments help you improve the document!

**Comment by muralidn** [comment]
Closing issue.
