### ISSUE TITLE
Responsibility for subsections 5.2.5 and 5.2.6 tests

### ISSUE THREAD

**Issue by gabrielasd** [muralidn/CAS741-Fall20#47]
Hello @muralidn,

Subsections 5.2.5 and 5.2.6 of the VnV present then Maintainability and Verifiability tests. Would it make sense to explicitly assign some of the review team members as responsible for these tests?

**Comment by muralidn** [comment]
Thanks @gabrielasd,  this is a good suggestion. I will look into this.

**Comment by muralidn** [comment]
I was not able to do this yet for this round of reviews. This will be done for any future VnV procedures.
