### ISSUE TITLE
Possible overlap between tests

### ISSUE THREAD

**Issue by gabrielasd** [muralidn/CAS741-Fall20#48]
Hi @muralidn,
The following question refers to tests in the subsections 5.1.1 and 5.1.2 of the vnV plan.

In the "Output test TC-PID-2" the equality of the Telapsed variable to the Tsim is verified. What would be the purpose of the "Overall simulation time TC-PID-3" test?

**Comment by muralidn** [comment]
Thank @gabrielasd. Yeah, this is an issue, will fix it.

**Comment by muralidn** [comment]
Issue fixed with  e48f234.
