### ISSUE TITLE
Output test

### ISSUE THREAD

**Issue by tingyuw** [muralidn/CAS741-Fall20#50]
You only have one test case for your output test, TC-PID-2. Are you going to verify the output for other sets of inputs? I know you have tested other input values in the simulation parameters test, but those cases are for the step time and simulation time not verifying the output correctness. Or are you planning to verify them at the same time? Do you have plans for testing other sets of inputs that meet the data constraints?

**Comment by muralidn** [comment]
Thanks for the comment Ting-Yu. Yes, the control variable, which is the output of the PID controller will be covered as part of the unit tests.

**Comment by muralidn** [comment]
Test case TC-PD-2-X, and TC-PD-14 were added to test the output when each value of the input is varied. This is available in the latest commit id, 1d4a54c.
