### ISSUE TITLE
Table of abbreviations

### ISSUE THREAD

**Issue by tingyuw** [muralidn/CAS741-Fall20#53]
Just a small comment. I don't think you need to include X in the table, but why is it don't care? Doesn't it mean references in your traceability table? Also, you can include the R - requirement and NFR - nonfunctional requirement in the abbreviation table.

**Comment by muralidn** [comment]
That is a good point. It was originally meant for my test case, but I decided against it but forgot to remove it from the abbreviations.

**Comment by muralidn** [comment]
Issue fixed with commit 838fe0d.
