### ISSUE TITLE
SRS scope update - Core updates

### ISSUE THREAD

**Issue by muralidn** [muralidn/CAS741-Fall20#55]
The current scope of the PID Controller is not compatible with Drasil. At the moment, Drasil cannot solve integrals, therefore the following scope changes are proposed to the project,

- Move the Integral Controller to the likely changes, just have a PD control in the loop.
- Use Laplace transforms to reduce the instance models of the PD controller into an Ordinary Differential Equation.
- Replace the power plant with a second-order system.

This ticket covers updates to the following section,

- Scope
- Theoretical model
- Instance model

**Comment by smiths** [comment]
Sounds good @muralidn.

**Comment by muralidn** [comment]
This issue is addressed with the Drasil Generated SRS, found in the following location,

https://github.com/muralidn/CAS741-Fall20/blob/master/docs/SRS/Drasil_SRS.pdf
https://github.com/muralidn/CAS741-Fall20/blob/master/docs/SRS/Drasil_SRS.tex
