### ISSUE TITLE
SRS review - Dr. Smith

### ISSUE THREAD

**Issue by muralidn** [muralidn/CAS741-Fall20#7]
@smiths  

Please review the first draft of the SRS (commit ID f454b8d). The artifacts are,

- https://github.com/muralidn/CAS741-Fall20/blob/master/docs/SRS/SRS.pdf
- https://github.com/muralidn/CAS741-Fall20/blob/master/docs/SRS/SRS.tex

A couple of points to note,

- I am in India so the date shows up as Oct-9th please ignore.
- The justification for all my assumption is that it may not be within the scope of Drasil. I don't that is appropriate for SRS, so I did not add this justification. 

Please review and share your feedback.

**Comment by smiths** [comment]
Thank you @muralidn.  I will review as soon as I can.

**Comment by muralidn** [comment]
Thank you Dr. @smiths.

Quick question, can I assign issues to myself and fix issues in SRS? I mean can I create issues myself and assign them to me?

**Comment by smiths** [comment]
Of course!  That is a very natural and common thing to do.  :smile:

**Comment by muralidn** [comment]
Thank You, Dr. Smith. Just pushed a new commit,  41ad20c with issue nos #10-#16 addressed. Please review when you get a chance.

**Comment by smiths** [comment]
Feedback on the SRS is available in a marked up version of the SRS in d3ff87d.  For any changes you intend to make, please create issues.
