### ISSUE TITLE
SRS review - Ting-Yu

### ISSUE THREAD

**Issue by muralidn** [muralidn/CAS741-Fall20#8]
@tingyuw

Please review the first draft of the SRS (commit ID f454b8d). The artifacts are,

- https://github.com/muralidn/CAS741-Fall20/blob/master/docs/SRS/SRS.pdf
- https://github.com/muralidn/CAS741-Fall20/blob/master/docs/SRS/SRS.tex

Please review and share your feedback.

**Comment by muralidn** [comment]
Hi @tingyuw,

FYI I found a few issues myself when peer-reviewing other documents. Therefore I created issues #10-#16 and addressed them with commit 41ad20c.

**Comment by tingyuw** [comment]
Hello, @muralidn 
I have reviewed your SRS. I don't have background knowledge on this topic, please forgive me if I ask some stupid questions.
Hope those comments help! Thank you.

**Comment by muralidn** [comment]
Thank You Ting-Yu!! Closing this issue as the review is complete.
