### ISSUE TITLE
SRS review - Sid

### ISSUE THREAD

**Issue by muralidn** [muralidn/CAS741-Fall20#9]
@shinsid 

Please review the first draft of the SRS (commit ID f454b8d). The artifacts are,

https://github.com/muralidn/CAS741-Fall20/blob/master/docs/SRS/SRS.pdf
https://github.com/muralidn/CAS741-Fall20/blob/master/docs/SRS/SRS.tex

Please review and share your feedback.

**Comment by muralidn** [comment]
Hi @shinsid ,

FYI I found a few issues myself when peer-reviewing other documents. Therefore I created issues #10-#16 and addressed them with commit 41ad20c.

**Comment by shinsid** [comment]
Hi Naveen @muralidn,

I reviewed your SRS document and it actually looks great and very understandable. Great job!
I have created issues for whatever minor things that I found. I hope it is useful.

Thanks,
Sid

**Comment by muralidn** [comment]
Thanks Sid. Closing this issue as the review is complete.
